kind: pipeline
type: docker
name: default

steps:
-   
    name: build
    image: rust:1.55
    commands:
        - cargo build --release --verbose --all

  
- 
    name: docker  
    image: plugins/docker
    settings:
        repo: phyzaitlu/voj-judger 
        username:
            from_secret: docker_username
        password:
            from_secret: docker_password
#    trigger:
#        event: tag
        
    when:
        event: tag