kind: pipeline
type: docker
name: default

steps:
-   
    name: build
    image: rust:1.55
    commands:
    #-   cargo build --verbose --all --release
    #-   cp target/release/voj_judger /release
    volumes:
    -   name: binary 
        path: /root/release 

  
- 
    name: push  
    image: plugins/docker
    settings:
        dockerfile: ci/Dockerfile
        repo: phyzaitlu/voj-judger 
        username:
            from_secret: docker_username
        password:
            from_secret: docker_password
    volumes:
    -   name: binary 
        path: /root/release 
        
    when:
        event: tag

volumes:
-   name: binary
    temp: {}
