name: Rust

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
    - name: Build
      uses: docker://rust:latest 
      with:
        args: cargo build --release --verbose

    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag voj-judger:$(date +%s)
