name: Rust

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest
    container:
      image: rust:latest
      volumes:
      - /workspace:/github/workspace
    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: cargo build --release --verbose
    - name: Run tests
      run: cargo test --verbose

  publish:

    runs-on: ubuntu-latest
    container: 
      image: registry
      volumes:
      - /workspace:/github/workspace
    steps:
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag voj-judger:$(date +%s)
